version: '3.1'

services:

  mongo:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - mongo-storage:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8800:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd

volumes: 
  mongo-storage:
    driver: local 